version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minioquickstar:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - minio
    environment:
      Minio__Endpoint: http://minio:9000
      Minio__AccessKey: minioadmin
      Minio__SecretKey: minioadmin
      Minio__BucketName: files
    ports:
      - "80:80"
      - "8080:8080"

volumes:
  minio-data:
